In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.3767, 0.7777, 0.3605],
        [0.6185, 0.2518, 0.5422],
        [0.8108, 0.6230, 0.8211],
        [0.1549, 0.8085, 0.9314],
        [0.1077, 0.6446, 0.2455]])


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5550, -0.2413,  0.5635],
        [ 0.2634,  1.3134, -0.4474],
        [-0.1252,  2.0503,  0.3292],
        [ 0.0117, -0.9455, -0.0569],
        [-1.6183,  0.3581,  0.1583]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.0232,  0.3803,  0.5654],
        [ 1.0995,  1.5502,  0.1301],
        [ 0.2100,  2.6374,  1.1576],
        [ 0.8665, -0.4795, -0.0128],
        [-0.8499,  1.1356,  0.6775]])


In [11]:
print(torch.add(x,y))

tensor([[ 0.0232,  0.3803,  0.5654],
        [ 1.0995,  1.5502,  0.1301],
        [ 0.2100,  2.6374,  1.1576],
        [ 0.8665, -0.4795, -0.0128],
        [-0.8499,  1.1356,  0.6775]])


In [12]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0232,  0.3803,  0.5654],
        [ 1.0995,  1.5502,  0.1301],
        [ 0.2100,  2.6374,  1.1576],
        [ 0.8665, -0.4795, -0.0128],
        [-0.8499,  1.1356,  0.6775]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.0232,  0.3803,  0.5654],
        [ 1.0995,  1.5502,  0.1301],
        [ 0.2100,  2.6374,  1.1576],
        [ 0.8665, -0.4795, -0.0128],
        [-0.8499,  1.1356,  0.6775]])


In [14]:
print(x[:,1])

tensor([-0.2413,  1.3134,  2.0503, -0.9455,  0.3581])


In [15]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0084])
-1.0084190368652344


In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
torch.cuda.is_available()

False